packages:
  - "packages/*"
  - "!**/test/**"
  - "!**/dist/**"
  - "!**/node_modules/**"
  - "!**/build/**"
  - "!**/coverage/**"
  - "!**/logs/**"
  - "!**/temp/**"
  - "!**/tmp/**"
  - "!**/cache/**"
  - "!**/logs/**"
  - "!**/temp/**" 